generator:
  target: "model.hififace.Generator"
  params:
    identity_extractor_config:
      f_3d_checkpoint_path: "model/Deep3DFaceRecon_pytorch/checkpoints/epoch_20.pth"
      f_id_checkpoint_path: "ms1mv3_arcface_r100_fp16_backbone.pth"

  optimizer:
    target: "torch.optim.AdamW"
    params:
      lr: 1e-4
      betas: 
      - 0
      - 0.999

discriminator:
  target: "model.multiscalediscriminator.MultiscaleDiscriminator"
  params:
    input_nc: 3

  optimizer:
    target: "torch.optim.AdamW"
    params:
      lr: 1e-4
      betas: 
      - 0
      - 0.999

g_loss:
  target: "model.loss.GExpressionLoss"
  params:
    f_3d_checkpoint_path: "model/Deep3DFaceRecon_pytorch/checkpoints/epoch_20.pth"
    f_id_checkpoint_path: "ms1mv3_arcface_r100_fp16_backbone.pth"
    sid_config:
      {}
    realism_config:
      {}

d_loss:
  target: "model.loss.DLoss"
  params: {}

dataset:
  train:
    target: "dataset.face_dataset.FaceDataset"
    params:
      data_root: "data/HDTF_face3dmmformer/train"
      split: "data/train_WDA_ChrisMurphy0_000.txt"
      same_rate: 20
    dataloader:
      batch_size: 8
      num_workers: 16
      drop_last: True
      shuffle: True

  validation:
    target: "dataset.HifiFaceParsingValDataset"
    params:
      img_root: "/"
      parsing_root: "/"
    dataloader:
      batch_size: 1
      shuffle: False
      num_workers: 8
